name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PHP
        run: sudo apt-get install -y php

      - name: Run tests
        run: |
          echo "Running PHP tests..."

      - name: Archive files
        run: |
          zip -r release.zip .  # 파일 압축
        continue-on-error: true

      - name: Upload artifact to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp release.zip s3://my-app-bucket/release.zip  # S3 버킷으로 업로드

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to AWS CodeDeploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          aws deploy create-deployment \
            --application-name MyPHPApp \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name MyPHPAppDeploymentGroup \
            --s3-location bucket=my-app-bucket,key=release.zip,bundleType=zip
