name: Deploy PHP to EC2 via CodeDeploy

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. AWS 자격 증명 설정 (Secrets에서 가져옴)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # 리전 설정

      # 3. 앱과 appspec.yml 파일을 압축 (SHA 값을 사용해 파일명 고유화)
      - name: Create deployment package
        run: zip -r ${{ github.sha }}.zip . -x ".git/*"

      # 4. S3에 zip 파일 업로드
      - name: Upload to S3
        run: |
          aws s3 cp ${{ github.sha }}.zip s3://codedeploy-front-sjy/${{ github.sha }}.zip

      # 5. CodeDeploy 배포 트리거
      - name: Deploy to CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name codedeploy-front-app-sjy \
            --deployment-group-name codedeploy-front-group-970728 \
            --s3-location bucket=codedeploy-front-sjy,key=${{ github.sha }}.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE
